services:
  db:
    image: postgres:17.5-bookworm
    container_name: postgres-datasource
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:8.0.1-bookworm
    container_name: redis-sessions
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    container_name: s3-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001
    volumes:
      - miniodata:/data
    networks:
      - app-network

  backend:
    image: noir777/whale-space-api:latest
    container_name: whale-space-api
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - minio
    networks:
      - app-network

  frontend:
    image: noir777/whale-space-frontend:latest
    container_name: whale-space-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:
  redisdata:
  miniodata:

networks:
  app-network:
    driver: bridge