server:
  address: ${SERVER_HOST}
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/v1
    session:
      cookie:
        max-age: 14d

spring:
  application:
    name: WhaleSpaceApi

  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
        ddl-auto: none

  session:
    timeout: 7d

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DATABASE}
      repositories:
        enabled: false

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  avatar-bucket: ${AVATAR_BUCKET}
