server:
  address: ${SERVER_HOST}
  port: ${SERVER_PORT}

  servlet:
    context-path: /api

    session:
      cookie:
        max-age: 14d

spring:
  application:
    name: WhaleSpaceApi

  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false

  session:
    timeout: 7d

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DATABASE}

      repositories:
        enabled: false