spring:
  config:
    import: "optional:file:./dev.env"

  jpa:
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG